### ISSUE TITLE
API v1/v2 switch is not effective if base_url already dictates it

### ISSUE THREAD

**Issue by jameswnl** [ansible/ansible_tower_client_ruby#114]
If the `connection` is initialized with a `base_url` that has `api version` in path, this `url_path_for_version` [here](https://github.com/ansible/ansible_tower_client_ruby/blob/master/lib/ansible_tower_client/connection.rb#L66) will be short circuit and the switch won't work.

**Comment by bdunne** [comment]
closed by https://github.com/ansible/ansible_tower_client_ruby/pull/117
