### ISSUE TITLE
with_lines not working with condition when

### ISSUE THREAD

**Issue by grb247** [ansible/ansible_tower_client_ruby#118]
SUMMARY
 - set_fact:
     existing_roles_file: "{{item}}"
   when: item | search("{{something}}")
   with_lines:  cat "{{path}}/to/file"
   ignore_errors: yes
Output is:

cat: /path/to/file: No such file or directory
fatal: [host_name]: FAILED! => {"failed": true, "msg": "lookup_plugin.lines(cat "/path/to/filr") returned 1"}

ISSUE TYPE
Bug Report
COMPONENT NAME
with_lines and when

ANSIBLE VERSION
"Ansible 2.4.0.0 "

it's working fine when i run this in my server but it's giving error while running on ansible tower.

**Comment by bdunne** [comment]
Hi @grb247 I think you have the wrong repo, this is for the ruby api client.

**Comment by grb247** [comment]
Hi @bdunne there is no repo for the ansible-tower where should i raise the issue related to tower

**Comment by gmcculloug** [comment]
@ghjm Can you help identify where this issue should be opened?

**Comment by ghjm** [comment]
@grb247 should open a support case at access.redhat.com.  Alternately, the issue can be raised against AWX, the open source upstream of Tower, at github.com/ansible/awx.
