### ISSUE TITLE
Getting project’s last update probably doesn’t work

### ISSUE THREAD

**Issue by Glutexo** [ansible/ansible_tower_client_ruby#125]
There is probably an issue with getting the project’s last update, which I introduced in #102. The problem is that I am [passing](https://github.com/ansible/ansible_tower_client_ruby/pull/102/files#diff-32924728a64494d2ca6ed15d1ad38acfR23) the project’s `related['last_update']` attribute to the [_api.project_updates.find_](https://github.com/ansible/ansible_tower_client_ruby/blob/f61c8cf2c1c50f3470f4a1a21f5b479433c60376/lib/ansible_tower_client/collection.rb#L30) method. The attribute is a relative URI, but the [_find_](https://github.com/ansible/ansible_tower_client_ruby/blob/f61c8cf2c1c50f3470f4a1a21f5b479433c60376/lib/ansible_tower_client/collection.rb#L30) method expects an ID. This could never actually work and I don’t know neither how come I didn’t notice nor how it could pass through a code review. But it’s there. 🙁

I didn’t actually run the code, I only inspected it and tried to figure out what’s going on there. But @AlexanderZagaynov is now working on it. I’d just like to make sure that it’s not resolved by some arbitrary URI parsing for this specific case, but rather in a more generic way: either by implementing a _Collection::find_by_url_ method, by allowing passing either an URI or an ID to the [_find_](https://github.com/ansible/ansible_tower_client_ruby/blob/f61c8cf2c1c50f3470f4a1a21f5b479433c60376/lib/ansible_tower_client/collection.rb#L30) method (with some checking) or by adding some [_BaseModel_](https://github.com/ansible/ansible_tower_client_ruby/blob/f61c8cf2c1c50f3470f4a1a21f5b479433c60376/lib/ansible_tower_client/base_model.rb) method that would check the URI for the model and scrape the ID from it.

Another problem is that the [test](https://github.com/ansible/ansible_tower_client_ruby/blob/f61c8cf2c1c50f3470f4a1a21f5b479433c60376/spec/project_spec.rb#L49) for this is not good. It just [mocks](https://github.com/ansible/ansible_tower_client_ruby/blob/f61c8cf2c1c50f3470f4a1a21f5b479433c60376/spec/project_spec.rb#L52) the [_find_](https://github.com/ansible/ansible_tower_client_ruby/blob/f61c8cf2c1c50f3470f4a1a21f5b479433c60376/lib/ansible_tower_client/collection.rb#L30) method and stubs it to return the project update. If we don’t want some functional tests for the whole process, at least this unit [test](https://github.com/ansible/ansible_tower_client_ruby/blob/f61c8cf2c1c50f3470f4a1a21f5b479433c60376/spec/project_spec.rb#L49) should be amended to check for the **correct** call.

**Comment by AlexanderZagaynov** [comment]
It will be fixed here: https://github.com/ansible/ansible_tower_client_ruby/pull/123/files#diff-32924728a64494d2ca6ed15d1ad38acfR21

And I'm already working on a new gem version from a scratch, so it makes no sense to evolve old one.
