### ISSUE TITLE
Gemify HashModel

### ISSUE THREAD

**Issue by djberg96** [ansible/ansible_tower_client_ruby#98]
We over at the azure-armrest gem might like to borrow the HashModel code as a base class for our own modelling.

Is there any chance that piece could be split off into its own repo so that we can then simply `require` it?

**Comment by bdunne** [comment]
I like the idea of sharing code, but I've been wanting to get rid of this code in particular.  It has caused many problems for us.

**Comment by djberg96** [comment]
Ours consumes too much memory because it's regenerating the model every time, so I'm hoping that yours is more memory efficient.

If you split it off, we can probably work out the issues together. :)
